### ISSUE TITLE
Home Assistant MQTT Message Not Being Published in v1.4

### ISSUE THREAD

**Issue by brusc** [happy-bubbles/presence#1]
Hello!

Thanks much for your latest update. After upgrading to 1.4, I'm not seeing any messages published to the happy-bubbles/presence/ha topic. Am I missing something obvious in the setup? 

Thanks much for your work on this!

**Comment by nemik** [comment]
Thanks for reporting this, please try 1.3 in the meantime and see if that helps. I'm investigating this and will hopefully have a fix soon.

**Comment by nemik** [comment]
commit 39a31d1831f552777974178095b082943aaa216a
and the new version 1.5 should have this fixed, i tested it to be working.

to test from commandline with mosquitto, make sure you subscribe to "happy-bubbles/presence/ha/#" topic because the topic changes for every location as per the Home Assistant room specs.

**Comment by brusc** [comment]
1.5 is working great. Thank you! I realized I might have been running 1.2 in my earlier post. I was following the steps from https://www.happybubbles.tech/presence/docs/rpi3_setup/ which uses the wget for version 1.2. Not sure if I changed it to 1.4 when I ran through the installer the first time.  

Thanks much for the quick fix!

**Comment by nemik** [comment]
No problem and thanks for the heads up! I've update the script and documentation, so you may want to just run the install script again.
