### ISSUE TITLE
Let users define how often to publish status

### ISSUE THREAD

**Issue by nemik** [happy-bubbles/presence#2]
from https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/happybubbles/eJ1awxKZ_gA

add a command-line option to only send the status every X seconds if someone wants that. But default to `1` if not defined.

**Comment by siam28** [comment]
I would like this feature too to avoid flooding my home assistant log. In addition to changing the update rate in the presence software, a firmware option to adjust the update rate from the actual units to the MQTT server would be useful too. This would be to prevent against flooding mosquitto's  logs.

**Comment by nemik** [comment]
@siam28 could you just turn down what you're logging on MQTT? I don't really want to add any update limits on the firmware/units themselves because it would really reduce their performance a lot. Their job is to forward the latest readings as fast as possible. How do you propose to reduce that?

I suggest you adjust your Mosquitto config to log only errors/warnings and not every message coming in. Take a look at this good tutorial on doing that: http://www.steves-internet-guide.com/mosquitto-logging/
You could also enable something like logrotate to purge out old logs to keep Mosquitto from filling up logs on your filesystem. 

But I really think too much logging is more of a problem than how often the presence system updates.

**Comment by nemik** [comment]
fixed with 0a1d7c3f5c3ab35bf41d56cca5e3baf604b7acf6

**Comment by siam28** [comment]
We could make these arguments (turning down logging, purging etc.) for not adding an option to change the publish status period from presence. 

I still think having the publish period configurable in the device firmware is a good feature. By default, you can have the devices send updates as fast possible like they currently do. So by default, the performance wouldn't be affected. For users who are using it for automation scenarios that don't require immediate updates, they can adjust if needed. Having options is never a bad thing.

Also, turning down logging for MQTT is not always possible or desirable because there could be some MQTT devices for which you want or need to see all messages.
